### ISSUE TITLE
Display total ascent with LineString tool

### ISSUE THREAD

**Issue by m1hax** [manuelkasper/sotlas-frontend#11]
Hi Manuel

When planning routes using the Sotlas LineString map tool, I have often thought it would helpful if the popup altitude graph displayed cumulative total ascent/descent figures. I wonder if it could be easily added? I attach a mock up example.

Thanks

![image](https://user-images.githubusercontent.com/68351586/114095926-f57c5200-98b5-11eb-8df8-2d61032f0bd0.png)

**Comment by manuelkasper** [comment]
Done!

**Comment by m1hax** [comment]
Thank you, that's very useful!
