### ISSUE TITLE
Filter to exclude summits not currently valid

### ISSUE THREAD

**Issue by m5evt** [manuelkasper/sotlas-frontend#15]
Is it possible to filter the map to hide summits not currently valid (e.g. deleted summits)? I've had a good search through the settings, am I missing something?

**Comment by manuelkasper** [comment]
<img width="221" alt="Screenshot 2022-01-26 at 20 29 58" src="https://user-images.githubusercontent.com/496413/151233216-97fd031f-9d47-4c60-86b8-bb35ca97f34e.png">

**Comment by m5evt** [comment]
Thank you. I feel foolish for not having seen this now. Thanks for your efforts with such a great resource.
