### ISSUE TITLE
Show filtered summits on map with a faint icon

### ISSUE THREAD

**Issue by m1hax** [manuelkasper/sotlas-frontend#18]
When filtering the map view by "not activated by", instead of completely hiding the already activated summits, show them discretely with an empty dotted circle or other faint marker.

This would be useful for easier map interpretation and for identifying re-activation opportunities of nearby summits when planning an activation trip. Particularly useful when the callsign has activated a number of summits in a year causing an area of the map to become quite empty.

And, perhaps the inverse arrangement for the 'Activated By' search option.

Interested to hear what others think, but I have thought this would be useful for some time now.

**Comment by manuelkasper** [comment]
Good idea – done!
