### ISSUE TITLE
Minor UI error when deleting an alert

### ISSUE THREAD

**Issue by ryandzink** [manuelkasper/sotlas-frontend#20]
I noticed this today when trying to delete alerts in an area with very weak cell service. In those conditions, the site throws an error that says 

> Could not delete spot: Network Error

Looks like https://github.com/manuelkasper/sotlas-frontend/blob/2192dff486ff543852972834602fbc51da8c8374/src/components/AlertsList.vue#L186 just needs to be updated to specify alerts rather than spots. Super trivial but I thought I would report it.

**Comment by manuelkasper** [comment]
Classic copy & paste mistake 😉 Thanks for the report!
