### ISSUE TITLE
Feature Request: Add official Austrian maps as additional map type

### ISSUE THREAD

**Issue by g84ycm** [manuelkasper/sotlas-frontend#22]
Add the following official Austrian maps to "Map Options" as additional "map type" (like openmaptiles, swisstopo, norkart, ...)

- https://maps.bev.gv.at/
- https://basemap.at/bmapp/index.html

![grafik](https://github.com/manuelkasper/sotlas-frontend/assets/55108566/d6af8768-0aa5-4954-ae44-a3bf4aa9d061)

**Comment by manuelkasper** [comment]
I have added basemap.at as a map option. The license of Austrian Map (maps.bev.gv.at) does not seem to allow such an integration (according to https://www.bev.gv.at/Services/Produkte/Austrian-Map/Austrian-Map-online.html “Nutzungsbedingungen”). However, I have added a link to Austrian Map on the summit detail pages (coordinates “Open” button).
