### ISSUE TITLE
Additional field for bonus points validity + link to association rules

### ISSUE THREAD

**Issue by stroobandt** [manuelkasper/sotlas-frontend#6]
Grüezi!

It would be great to have the following in the summit pop-up / info page:

- An extra field or hoover tip with the bonus point validity period,
![bonus points](https://imgur.com/uyhMsXj.png)
- A direct link to the association's rules page.

Vielen Dank!

**Comment by manuelkasper** [comment]
Hello,

I've had a look and found the following:

- Bonus validity period: It seems that the only way to get this is from the database API (https://api-db.sota.org.uk/admin/summit_history?summitID=xxx), but then one needs to look up the summit ID first. The regular API (https://api2.sota.org.uk/api/summits/3Y/BV-001) that SOTLAS uses does not return it. I assume if the bonus validity period was shown on https://summits.sota.org.uk/ (currently it's not), then they would make the API return it as well :wink:
- Association rules: The PDF filenames can be obtained from https://api2.sota.org.uk/api/associations/XX, but many are hopelessly outdated or missing altogether, and it seems that the MT wants to move away from PDF-based ARMs to something generated from the database anyway.

Manuel HB9DQM
