### ISSUE TITLE
Add Bing Maps links for UK region summit pages

### ISSUE THREAD

**Issue by m1hax** [manuelkasper/sotlas-frontend#8]
Please add a 'Bing Maps (OS)' link to the 'Open' drop down menu on summit pages in the UK regions. Microsoft has a licence to use the high detail Ordnance Survey maps on its site. The OS Maps site that is currently linked requires a paid subscription to view these same map views. Here is a sample URL for a Bing Maps view of GW/MW-025:

https://www.bing.com/maps?cp=52.09156~-3.2348&lvl=15&style=s&v=2

Compared with the (free) view of the same location on the OS Maps website at https://osmaps.ordnancesurvey.co.uk/52.09156,-3.23480,15/pin the Bing map is clearly better!

**Comment by manuelkasper** [comment]
Hmm, when I access the two links from here, Bing Maps shows only a very basic road map and you cannot even tell where the summit is, while the OS Maps are quite detailed. Could this have to do with accessing Bing from an IP address outside the UK?

**Comment by m1hax** [comment]
I have just done some tests using an IP address from outside Europe. The Ordnance Survey map did not change appearance, but Bing Maps showed a very basic map as you describe. I attach two screenshots showing the same Bing Maps view of GW/MW-025, one with a UK IP address and one without:

![image](https://user-images.githubusercontent.com/68351586/109062949-7e617480-76e0-11eb-8aa9-0c546a78c52a.png)

![image](https://user-images.githubusercontent.com/68351586/109062959-80c3ce80-76e0-11eb-85a5-0125683fa896.png)

The high detail view is only available with a paid subscription on the Ordnance Survey website. As Bing provides the high detail OS map views for free to UK users it seems appropriate to add an additional 'Bing Maps' link to summits in the UK regions.

**Comment by manuelkasper** [comment]
Thanks for the analysis, that makes sense then! I've added the Bing Maps link (globally, as I figured there might be other countries where Bing maps are at least as useful as Google Maps).

**Comment by m1hax** [comment]
Thank you! I think if nothing else UK activators will appreciate having this option when looking at summits.
