### ISSUE TITLE
Additional regional map viewer links

### ISSUE THREAD

**Issue by m1hax** [manuelkasper/sotlas-frontend#9]
Hi Manuel.

Please see this page: https://reflector.sota.org.uk/t/national-mapping-viewers/25232

Similar to our recent discussion around Bing maps for the UK, the SOTA team have added a number of additional map viewer links to summit pages, such as http://kortasja.lmi.is for TF (Iceland).

I thought it would be nice to incorporate these additional country-specific map links to the SOTL.AS website too.

Thanks
Richard M1HAX

**Comment by manuelkasper** [comment]
The logic for the external map links in the “Open” menu next to the coordinates shown on SOTLAS (either by right-clicking the map, or at the top of a summit details page) is here:

https://github.com/manuelkasper/sotlas-frontend/blob/00ac125a03a651bc5ab5fcdd31b5db29ea9360f0/src/components/Coordinates.vue#L89-L186

So far the map links that aren't available worldwide (swisstopo, CalTopo etc.) are filtered by matching on a rough range of latitudes/longitudes. That way it works even if no summit reference is known (because the user right-clicked the map). One could also match on `this.reference`, but then it would only work on summit details pages.

PR appreciated :wink:

**Comment by m1hax** [comment]
Assign it to me if you can, I will start working on it now.

**Comment by manuelkasper** [comment]
Thanks!

**Comment by m1hax** [comment]
Hi Manuel

I have submitted a PR that adds support for some of the maps referenced above.

Unfortunately all of the other additional mapping websites use coordinate schemes in their URLs other than decimal degrees. Further investigation on whether each website supports a different URL structure for decimal degrees, but it seems likely a conversion function to convert decimal degrees to the required coordinate format is needed. That is outside my JavaScript capabilities!

I include below a table of the other regional maps not yet implemented with example URLs.

Regards
Richard

| Region                     | Country                       | Service       | ExampleLink                                                                                                                                                                                                         |
| -------------------------- | ----------------------------- | -------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| ON                         | Belgium                       | NGI TopoMap    | https://topomapviewer.ngi.be/?l=en&x=772402.12&y=633792.36&zoom=9&baseLayer=classic.maps                                                                                                                             |
| LX                         | Luxembourg                    | Geoportal (LX) | https://map.geoportail.lu/theme/main?version=3&zoom=16&X=662540&Y=6441515&lang=fr&rotation=0&layers=206&opacities=1&bgLayer=blank                                                                                    |
| SM                         | Sweden                        | Lantmateriet   | https://kso.etjanster.lantmateriet.se/?e=606969.8969037473&n=7466004.2842235435&z=11&profile=default\_background\_noauth                                                                                             |
| OZ                         | Denmark                       | SDFE           | https://sdfekort.dk/spatialmap?profile=sdfekort&wkt=POINT(541668.6710640951+6215819.897226054)&layers=theme-dtk\_4cm\_1980\_2001\_daf&mapext=540668.6710640951+6214819.897226054+542668.6710640951+6216819.897226054 |
| OY                         | Faroe Islands                 | Føroyakort     | https://kort.foroyakort.fo/kort/?center=216008.14160288766,917448.8275311496,5316&level=9                                                                                                                            |
| DL                         | Germany (Alpine)              | Karten des BKG | https://sg.geodatenzentrum.de/web\_bkg\_webmap/applications/bkgmaps/minimal.html?zoom=11&lat=5255697.925478942&lon=651135.5799711612&layers=B000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFT                 |
| OE                         | Austria                       | Basemap.at     | https://basemap.at/bmapp/index.html#{%22center%22:\[1834055.402513658,6086134.214288427\],%22zoom%22:16,%22rotation%22:0,%22layers%22:%220100000000%22}                                                              |
| LY                         | Lithuania                     | Geoportal (LT) | https://www.geoportal.lt/map/#s=3346&x=529840.589207059&y=6054988.898883883&l=8&b=default                                                                                                                            |
| YL                         | Latvia                        | LGIA           | https://kartes.lgia.gov.lv/karte/?x=242236.42817348335&y=726266.7944164092&lx=5565.0&ly=3130.313&l=1,8,9,10,13,14,15,40,51,62,63,64,65,66,67,68,69,70                                                                |
| VK1 (using the VK2 server) | Australia - Capital Territory | SIXmaps        | https://portal.spatial.nsw.gov.au/portal/apps/webappviewer/index.html?center=16583142.09203409,-4282022.982918631,102100&level=16                                                                                    |
| VK2                        | Australia - NSW               | SIXmaps        | https://portal.spatial.nsw.gov.au/portal/apps/webappviewer/index.html?center=16583142.09203409,-4282022.982918631,102100&level=16                                                                                    |
| VK3                        | Australia - Victoria          | MapshareVIC    | https://mapshare.vic.gov.au/MapshareVic/?layerTheme=5&scale=3000&basemap=bWFwc2NhcGUgY29sb3Vy&center=2278690.3723971564,2475219.777798267                                                                            |
| VK4                        | Australia - Queensland        | QTopo          | https://qtopo.information.qld.gov.au/?center=16202128.870895952,-1985664.9413225895,102100&level=16                                                                                                                  |
| 4X                         | Israel                        | Govmap         | https://www.govmap.gov.il/?c=164861.12074154348,490402.3836034542&z=4&b=9                                                                                                                                            |
| DM                         | Germany (Low Mountains)       | Karten des BKG | https://sg.geodatenzentrum.de/web\_bkg\_webmap/applications/bkgmaps/minimal.html?zoom=11&lat=5430753.784582367&lon=783921.4674702662&layers=B000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFT                 |
| DM/RP                      | Rhineland-Palatinate          | maps.rlp.de    | https://maps.rlp.de/?layerIDs=152,3&visibility=true,true&transparency=0,0&center=362399.3759635635,5510406.879758297&zoomlevel=8                                                                                     |
| DM/BM                      | Bavarian low mountain ranges  | Karten des BKG | https://sg.geodatenzentrum.de/web\_bkg\_webmap/applications/bkgmaps/minimal.html?zoom=11&lat=5458133.889654329&lon=799334.1097643182&layers=B000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFT                 |
| TF                         | Iceland                       | Kortasjá       | http://kortasja.lmi.is/mapview/?application=kortasja&lang=is&center=571274.5878264972,419738.3709118515&zoom=11&layers=219,225,228,286,221%20X                                                                       |
| LZ                         | Bulgaria                      | Kade           | https://kade.si/#map=15/2671195.45/5192366.81/0                                                                                                                                                                      |

**Comment by manuelkasper** [comment]
Merged and deployed, thanks!

**Comment by m1hax** [comment]
I'm sorry to say some of the new links don't seem to function properly. The VK5 LocationSA for example works properly. But the Jan Mayen, Svalbard, Croatia summit links I have tested result in loading URLs where the longitude parameter is not replaced with its numerical value. For example, JX/JM-001 map link gives URL `https://topojanmayen.npolar.no/?lat=71.0822&long={this.longitude}&zoom=8&layer=map`. Looking at the code I'm unclear why the VK5 longitude is populated but the others aren't?

**Comment by manuelkasper** [comment]
> I'm sorry to say some of the new links don't seem to function properly.

Reload the page, I have already fixed the links :smile: (https://github.com/manuelkasper/sotlas-frontend/commit/78c4cc0ead80d75e0fd247fd1ec5739510a2494f)

**Comment by m1hax** [comment]
Sorry, typo on my part. Also noticed that TopoSvalbard only works with DD parameters with six decimal places. I think the lat/long variables need to be treated with a `.toFixed(6)` function?

**Comment by manuelkasper** [comment]
> Also noticed that TopoSvalbard only works with DD parameters with six decimal places. I think the lat/long variables need to be treated with a `.toFixed(6)` function?

Seems to work for me even with more decimals, e.g. https://toposvalbard.npolar.no/?lat=78.4306588&long=21.0063115&zoom=8&layer=map

**Comment by manuelkasper** [comment]
> Also noticed that TopoSvalbard only works with DD parameters with six decimal places. I think the lat/long variables need to be treated with a `.toFixed(6)` function?

I have added this to TopoSvalbard and TopoJanMayen now.

**Comment by vk3arr** [comment]
Hi Manuel, if you want the code we use for summits.sota to do the conversions for the non-EPSG:3857 map viewers, I'll try to whip up a PR for you

**Comment by manuelkasper** [comment]
> Hi Manuel, if you want the code we use for summits.sota to do the conversions for the non-EPSG:3857 map viewers, I'll try to whip up a PR for you. All of our handling is done per-association (using regex matching where viewers cross multiple associations)

Hi Andrew, that would be great – thank you!

**Comment by m1hax** [comment]
I think that this issue can be closed? It appears that Coordinates.vue has been updated to support the non-EPSG:3857 map viewers described above.

**Comment by manuelkasper** [comment]
Yes, thanks – I forgot to close it.
